language: python

jobs:
  include:
    - python: 3.5
    - python: 3.6
    - python: 3.7
    - python: 3.8
    - python: 3.9

install:
  - pip install tox tox-travis coveralls
script:
  - tox
after_success:
  coveralls
