language: python

jobs:
  include:
    - python: 2.7
    - python: 3.4
    - python: 3.5
      dist: xenial
      language: python
    - python: 3.6
      dist: xenial
      language: python
    - python: 3.7
      dist: xenial
      sudo: true
    - python: 3.8
      dist: xenial
      sudo: true
    - python: 3.9
      dist: xenial
      sudo: true

install:
  - pip install -U packaging  # fix for Python3.4 build
  - pip install tox tox-travis coveralls
script:
  - tox
after_success:
  coveralls
